# Part 1: Launch a Duet Server and upload data

In [2]:
import syft as sy
duet = sy.launch_duet(loopback=True)

TypeError: Descriptors cannot be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates

In [2]:
import torch as th
import numpy as np

In [3]:
data = th.FloatTensor(np.array([5, 15, 25, 35, 45, 55]).reshape(-1, 1))

data = data.tag("DO1 data")
data = data.describe("Dataset of 6 samples, 1 feature")

data_ptr = data.send(duet, searchable=True)

In [4]:
duet.store.pandas

ID        Tags  \
0  <UID: 95b50c81d41f48f280bfb4ed88ff3c62>  [DO1 data]   

                       Description  
0  Dataset of 6 samples, 1 feature

In [5]:
data

tensor([[ 5.],
        [15.],
        [25.],
        [35.],
        [45.],
        [55.]])

In [6]:
duet.requests.add_handler(
    action="accept",
    print_local=True,  # print the result in your notebook
)

> HANDLER Request : To evaluate training progress
Value: 1050.6131591796875
> HANDLER Request : To evaluate training progress
Value: 833.8958129882812
> HANDLER Request : To evaluate training progress
Value: 643.0696411132812
> HANDLER Request : To evaluate training progress
Value: 478.4125671386719
> HANDLER Request : To evaluate training progress
Value: 339.91876220703125
> HANDLER Request : To evaluate training progress
Value: 227.21815490722656
> HANDLER Request : To evaluate training progress
Value: 32.8933219909668
> HANDLER Request : To evaluate training progress
Value: 9.448577880859375
> HANDLER Request :
Value: [Parameter containing:
tensor([[0.6305]], requires_grad=True), Parameter containing:
tensor([1.1781], requires_grad=True)]
> HANDLER Request :
Value: in_features=1, out_features=1, bias=True
> HANDLER Request :
Value: OrderedDict([('weight', tensor([[0.6305]])), ('bias', tensor([1.1781]))])
